### ISSUE TITLE
get method and the useless %options parameters

### ISSUE THREAD

**Issue by jackdeguest** [Corion/www-mechanize-phantomjs#15]
Hello Max Maischein,

I have been scratching my head for hours trying to understand what is wrong in my code that the following request would not work as advertised in your documentation:
`my $resp = $mech->get( $url, ':content_file' => $file );
`
Then, desperately, I looked at the code of the module and saw that the options passed actually do nothing.... Or am I reading this wrong?
Here is the current get method in the WWW::Mechanize::PhantomJS package.
```
sub get {
    my ($self, $url, %options ) = @_;
    # We need to stringify $url so it can pass through JSON
    my $phantom_res= $self->driver->get( "$url" );
    $self->post_process;
    $self->update_response( $phantom_res );
};

```

Kind regards,
Jacques Deguest

**Comment by Corion** [comment]
Hello Jacques,

yes, sorry - that part is documented wrong as there is no download 
method that downloads directly to a file :-/

-max

Am 16.05.2016 um 12:50 schrieb Jacques Deguest:

**Comment by jackdeguest** [comment]
Thank you max.

Any possibility to implement it? Otherwise, I will need to instantiate a separate WWW::Mechanize object just for that purpose. Not a big deal, but still I wish I could avoid it.

Jacques

**Comment by Corion** [comment]
Hello Jacques,

I don't see an easy way to implement the method in a sensible manner, 
because PhantomJS doesn't offer a way to save the incoming result to a 
file directly.

I can add a wrapper that will load the result into memory and then write 
the file to disk afterwards, but that will only help with 
API-compatibility, not with memory usage...

-max

Am 16.05.2016 um 18:42 schrieb Jacques Deguest:

**Comment by jackdeguest** [comment]
Sure, I understand.
And how about inheriting from WWW::Mechanize?
You could then easily use the inherited features as needed through the SUPER:: feature?

Jacques

**Comment by Corion** [comment]
Hello Jacques,

I've just looked at it, and PhantomJS does not support downloading files 
at all. I will update the documentation.

Just inheriting from WWW::Mechanize won't work because the backend is 
completely different.

-max

Am 16.05.2016 um 18:49 schrieb Jacques Deguest:
