### ISSUE TITLE
Proxy type is always direct in info logs proxy":{"proxyType":"direct"}}

### ISSUE THREAD

**Issue by aaryabhatt** [Corion/www-mechanize-phantomjs#17]
Hi,

I am trying to connect this with tor proxy, but it is not connecting to proxy  and always go directly.
see below my code.

`use WWW::Mechanize::PhantomJS;
 my $mech = WWW::Mechanize::PhantomJS->new(
                   phantomjs_arg => [ "--proxy=127.0.0.1:9050 --proxy-type=socks5 --ssl-protocol=any --ignore-ssl-errors" ],
                   log => 'INFO' );
            
my $url = "https://example.com/home";

$mech->get( $url );
` 
info logs are given below
[INFO  - 2018-04-02T06:32:40.966Z] GhostDriver - Main - running on port 8910
[INFO  - 2018-04-02T06:32:42.667Z] Session [a5c1ef30-363f-11e8-a95c-e32e0ebfd9d2] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"}
[INFO  - 2018-04-02T06:32:42.667Z] Session [a5c1ef30-363f-11e8-a95c-e32e0ebfd9d2] - page.customHeaders:  - {}
[INFO  - 2018-04-02T06:32:42.667Z] Session [a5c1ef30-363f-11e8-a95c-e32e0ebfd9d2] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"**proxy":{"proxyType":"direct"}}**
[INFO  - 2018-04-02T06:32:42.667Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: a5c1ef30-363f-11e8-a95c-e32e0ebfd9d2

proxy is working fine. I tried to test it with bash
phantomjs --proxy=127.0.0.1:9050 --proxy-type=socks5 --ssl-protocol=any  page_load.js
that wrks fine.

**Comment by Corion** [comment]
Please try passing the parameters as a list, not as one single string:

  my $mech = WWW::Mechanize::PhantomJS->new(
    phantomjs_arg => [ "--proxy=127.0.0.1:9050", "--proxy-type=socks5", "--ssl-protocol=any", "--ignore-ssl-errors" ],
 log => 'INFO' );

(this might appear a second time as soon as my reply mail arrives)

**Comment by aaryabhatt** [comment]
@Corion thanks for your quick reply. I tried this code and now I am getting below error

Error: Unknown option: port
Selenium server did not return proper status at /usr/local/share/perl/5.22.1/Selenium/Remote/Driver.pm line 415.

**Comment by Corion** [comment]
Hmm - this is weird - you seem to be the first person who encounters this problem, but I can reproduce it locally as well. You will need to change the "--port" to "--webdriver" in lib/WWW/Mechanize/PhantomJS.pm - I wonder why this error is only showing now ...

**Comment by aaryabhatt** [comment]
there is mulitple PhantomJS.pm file on my ubunut 16.04 machine, only thing take into effect by changing in 
/usr/local/share/perl/5.22.1/WWW/Mechanize/PhantomJS.pm which change the error little, then giving below error

before change
        push @{ $options->{ launch_arg }}, "--port=$options->{ port }";

after change 
      push @{ $options->{ launch_arg }}, "--webdriver=$options->{ port }";

Error: Unknown option: logLevel
Selenium server did not return proper status at /usr/local/share/perl/5.22.1/Selenium/Remote/Driver.pm line 415.

**Comment by aaryabhatt** [comment]
Corion thank you very much, it solved the issue, now requests are going through the proxy server.
that is sufficient for me.

But if Check the info logs, it is still showing direct proxy in proxyType, may be issue could be other thing not known to me. Just point it here for your info, see the below logs.

[INFO  - 2018-04-02T07:31:57.223Z] GhostDriver - Main - running on port 8910
[INFO  - 2018-04-02T07:31:59.144Z] Session [ed956910-3647-11e8-8532-e112d9726966] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1"}
[INFO  - 2018-04-02T07:31:59.145Z] Session [ed956910-3647-11e8-8532-e112d9726966] - page.customHeaders:  - {}
[INFO  - 2018-04-02T07:31:59.145Z] Session [ed956910-3647-11e8-8532-e112d9726966] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}

thanks again.

**Comment by Corion** [comment]
I think my diagnosis was somewhat misguided and there is something else wrong with your setup. The changes needed in your case were not necessary in my case. It seems that phantomjs is missing the script name for Ghostdriver in your case.

But if everything works for you and the connection goes through tor, it's great. I would double-check, since if PhantomJS claims it's not using a proxy, that's worth a second check.
